version: '3.8'
services:
  db:
    image: postgres:13
    container_name: stock_trading_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock-trading
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: stock_trading_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/stock-trading"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: